09.CSharp MVC Frameworks/Exercises ASP.NET Core Razor & Filters/CameraBazaar/CameraBazaar.Web/Controllers/CameraController.cs
using CameraBazaar.Data;
using CameraBazaar.Services.Contracts;
using CameraBazaar.Services.Models;
using CameraBazaar.Web.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CameraBazaar.Web.Controllers
{
    public class CameraController : Controller
    {
        private readonly ICameraService cameraService;
        private readonly CameraBazaarDbContext db;

        public CameraController(ICameraService cameraService, CameraBazaarDbContext db)
        {
            this.cameraService = cameraService;
            this.db = db;
        }

        [Authorize]
        public IActionResult Add()
        {
            if (!this.cameraService.UserIsBanned(this.User.GetUserId()))
            {
                return View(new AddCameraModel());
            }

            return View("Banned");
        }

        [Authorize]
        [HttpPost]
        public IActionResult Add(AddCameraModel addCameraModel)
        {
            if (this.cameraService.UserIsBanned(this.User.GetUserId()))
            {
                return BadRequest();
            }

            if (this.ModelState.IsValid)
            {
                this.cameraService.AddCam(this.User.GetUserId(), addCameraModel);

                return RedirectToAction("Index", "Home");
            }

            return View(addCameraModel);
        }

        public IActionResult Details(int? id)
        {
            if (this.cameraService.CameraExists(id))
            {
                CameraFullDetailsModel cameraFullDetailsModel = this.cameraService.GetCameraFullDetails(id);

                return View(cameraFullDetailsModel);
            }

            return BadRequest();
        }

        [Authorize]
        public IActionResult Edit(int? id)
        {
            if (id != null && this.cameraService.CameraExists(id) && this.cameraService.UserCanEditCamera(this.User.GetUserId(), id.Value))
            {
                EditCameraModel editCameraModel = this.cameraService.GetCameraCompleteEditInfromatio(id.Value);

                return View(editCameraModel);
            }

            return BadRequest();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(EditCameraModel editCameraModel)
        {
            if (this.ModelState.IsValid && this.cameraService.CameraExists(editCameraModel.CameraId) && this.cameraService.UserCanEditCamera(this.User.GetUserId(), editCameraModel.CameraId))
            {
                this.cameraService.EditCamera(editCameraModel);

                return RedirectToAction("Index", "Home");
            }

            return View(editCameraModel);
        }

        [Authorize]
        public IActionResult Delete(int? id)
        {
            if (id != null && this.cameraService.CameraExists(id) && this.cameraService.UserCanEditCamera(this.User.GetUserId(), id.Value))
            {
                EditCameraModel editCameraModel = this.cameraService.GetCameraCompleteEditInfromatio(id.Value);

                return View(editCameraModel);
            }

            return BadRequest();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Destroy(int? cameraId)
        {
            if (cameraId != null && this.cameraService.CameraExists(cameraId) && this.cameraService.UserCanEditCamera(this.User.GetUserId(), cameraId.Value))
            {
                this.cameraService.DeleteCamera(cameraId.Value);

                return RedirectToAction("Index", "Home");
            }

            return BadRequest();
        }
    }
}

09.CSharp MVC Frameworks/Exercises ASP.NET Core Razor & Filters/CameraBazaar/CameraBazaar.Web/Controllers/ProfilesController.cs
using CameraBazaar.Services.Contracts;
using CameraBazaar.Services.Models;
using CameraBazaar.Web.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CameraBazaar.Web.Controllers
{
    [Authorize]
    public class ProfilesController : Controller
    {
        private readonly ICameraService cameraService;
        private readonly IUserService userService;

        public ProfilesController(ICameraService cameraService, IUserService userService)
        {
            this.cameraService = cameraService;
            this.userService = userService;
        }

        public IActionResult Details(string id)
        {
            var model = new ProfileViewModel();

            if (this.userService.UserExistsById(id))
            {
                model.UserDetails = this.userService.GetUserProfile(id);
                model.Cameras = this.cameraService.GetCamerasDetailsForUser(id);

                return View(model);
            }

            return BadRequest();
        }

        public IActionResult Edit(string id)
        {
            if (this.userService.UserExistsById(id) && this.User.GetUserId() == id)
            {
                EditProfileModel editProfileModel = this.userService.GetProfileEditInfo(id);

                return View(editProfileModel);
            }

            return BadRequest();
        }

        [HttpPost]
        public IActionResult Edit(EditProfileModel editProfileModel)
        {
            if (this.ModelState.IsValid)
            {
                if (this.User.GetUserId() == editProfileModel.UserId)
                {
                    this.userService.EditProfile(editProfileModel);

                    return RedirectToAction("Details", new { id = editProfileModel.UserId });
                }

                return Unauthorized();
            }

            return View(editProfileModel);
        }
    }
}

09.CSharp MVC Frameworks/Exercises ASP.NET Core Razor & Filters/CameraBazaar/CameraBazaar.Web/Views/Shared/_CameraPartial.cshtml
@model CameraShortDetailsModel
<div class="col-md-10 col-md-offset-1">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="col-md-2">
                <img src="@Model.ImageUrl" alt="@Model.Model" class="img-responsive" />
            </div>
            <div class="col-md-8">
                <div class="col-md-12">
                    <div class="col-md-6">
                        <h3>@Model.Make/@Model.Model</h3>
                    </div>
                    <div class="col-md-6 text-right">
                        <h3>$@Model.Price.ToString("F2")</h3>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-6">
                        <a asp-action="Details" asp-controller="Camera" asp-route-id="@Model.CameraId">Details</a>
                    </div>
                    <div class="col-md-6 text-right">
                        @if (Model.InStock)
                        {
                            <span class="text-success"><strong>IN STOCK</strong></span>
                        }
                        else
                        {
                            <span class="text-danger"><strong>OUT OF STOCK</strong></span>
                        }
                    </div>
                </div>
            </div>
            @if (this.User.GetUserId() != null && this.User.GetUserId() == Model.SellerId)
            {
                <div class="col-md-2">
                    <a class="btn btn-info form-control" asp-action="Edit" asp-controller="Camera" asp-route-id="@Model.CameraId">Edit</a>
                    <br />
                    <a class="btn btn-warning form-control" asp-action="Delete" asp-controller="Camera" asp-route-id="@Model.CameraId">Delete</a>
                </div>
            }
        </div>
    </div>
</div>

09.CSharp MVC Frameworks/Exercises ASP.NET Core Razor & Filters/CameraBazaar/CameraBazaar.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CameraBazaar.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CameraBazaar.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Camera" asp-action="Add">Add camera</a></li>
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a asp-area="" asp-controller="Profiles" asp-action="Details" asp-route-id="@this.User.GetUserId()" title="Seller Profile">My Seller Profile</a>
                        </li>
                    }
                    @if (this.User.IsInRole("Admin"))
                    {
                        <li class="nav navbar-right">
                            <a asp-action="All" asp-controller="Admin">Admin</a>
                        </li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <div class="col-md-12">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; 2017 - CameraBazaar.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>