09.CSharp MVC Frameworks/Exercises ASP.NET Essentials/CarDealerSystem/CarDealerSystem.Web/Controllers/PartsController.cs
using CarDealerSystem.Services.Contracts;
using CarDealerSystem.Services.Models.Parts;
using Microsoft.AspNetCore.Mvc;

namespace CarDealerSystem.Web.Controllers
{
    public class PartsController : Controller
    {
        private readonly IPartService partService;

        public PartsController(IPartService partService)
        {
            this.partService = partService;
        }

        public IActionResult All()
        {
            AllPartsModel model = this.partService.GetAllParts();

            return this.View(model);
        }

        public IActionResult Edit(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            EditDeletePartModel model = this.partService.GetPartInfo(id.Value);

            if (model is null)
            {
                return RedirectToAction("All");
            }

            return this.View(model);
        }

        [HttpPost]
        public IActionResult Edit(EditDeletePartModel model)
        {
            if (this.ModelState.IsValid)
            {
                this.partService.UpdatePart(model);

                return RedirectToAction("All");
            }

            return View(model);
        }

        public IActionResult Delete(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            EditDeletePartModel model = this.partService.GetPartInfo(id.Value);

            if (model is null)
            {
                return RedirectToAction("All");
            }

            return this.View(model);
        }

        [HttpPost]
        public IActionResult Delete(EditDeletePartModel model)
        {
            if (model.Id.HasValue)
            {
                this.partService.DeletePart(model.Id.Value);

                return RedirectToAction("All");
            }

            return View(model);
        }

        public IActionResult Add()
        {
            AddPartModel model = this.partService.GetPartModelWithSuppliers();

            return this.View(model);
        }

        [HttpPost]
        public IActionResult Add(AddPartModel model)
        {
            if (this.ModelState.IsValid)
            {
                this.partService.AddPart(model);

                return RedirectToAction("Add");
            }

            model.Suppliers = this.partService.GetPartModelWithSuppliers().Suppliers;

            return this.View(model);
        }
    }
}

09.CSharp MVC Frameworks/Exercises ASP.NET Essentials/CarDealerSystem/CarDealerSystem.Web/Views/Parts/Add.cshtml
@model AddPartModel
@{
    this.ViewData["Title"] = "Add a part";
}

<form asp-action="Add" method="post">
    <label asp-for="@Model.Name"></label>
    <input asp-for="@Model.Name" />
    <span asp-validation-for="@Model.Name"></span>
    <br />
    <label asp-for="@Model.Price"></label>
    <input asp-for="@Model.Price" />
    <span asp-validation-for="@Model.Price"></span>
    <br />
    <label asp-for="@Model.Quantity"></label>
    <input asp-for="@Model.Quantity" />
    <span asp-validation-for="@Model.Quantity"></span>
    <br />
    <label asp-for="@Model.SupplierId"></label>
    <select asp-for="@Model.SupplierId">
        @foreach (var supp in Model.Suppliers)
        {
            <option value="@supp.Id">@supp.Name</option>
        }
    </select>
    <span asp-validation-for="@Model.SupplierId"></span>
    <br />
    <input type="submit" value="Submit" />
</form>

09.CSharp MVC Frameworks/Exercises ASP.NET Essentials/CarDealerSystem/CarDealerSystem.Web/Views/Parts/All.cshtml
@model AllPartsModel
@{
    this.ViewData["Title"] = "All parts";
}

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var part in Model.Parts)
        {
            <tr>
                <td>@part.Name</td>
                <td>@part.Price.ToString("F2")</td>
                <td>
                    <a class="btn btn-warning" asp-controller="Parts" asp-action="Edit" asp-route-id="@part.Id">Edit</a>
                    <a class="btn btn-danger" asp-controller="Parts" asp-action="Delete" asp-route-id="@part.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

09.CSharp MVC Frameworks/Exercises ASP.NET Essentials/CarDealerSystem/CarDealerSystem.Web/Views/Parts/Delete.cshtml
@model EditDeletePartModel
@{
    this.ViewData["Title"] = "Delete part";
}

<form asp-controller="Parts" method="post">
    <input asp-for="@Model.Id" type="hidden" />
    <label asp-for="@Model.Name"></label>
    <input asp-for="@Model.Name" disabled />
    <br />
    <label asp-for="@Model.Price"></label>
    <input asp-for="@Model.Price" disabled />
    <br />
    <label asp-for="@Model.Quantity"></label>
    <input asp-for="@Model.Quantity" disabled />
    <br />
    <input type="submit" value="Delete" />
</form>

09.CSharp MVC Frameworks/Exercises ASP.NET Essentials/CarDealerSystem/CarDealerSystem.Web/Views/Parts/Edit.cshtml
@model EditDeletePartModel
@{
    this.ViewData["Title"] = "Edit part";
}

<form asp-controller="Parts" method="post">
    <input asp-for="@Model.Id" type="hidden" />
    <label asp-for="@Model.Name"></label>
    <input asp-for="@Model.Name" disabled />
    <br />
    <label asp-for="@Model.Price"></label>
    <input asp-for="@Model.Price" />
    <span asp-validation-for="@Model.Price"></span>
    <br />
    <label asp-for="@Model.Quantity"></label>
    <input asp-for="@Model.Quantity" />
    <span asp-validation-for="@Model.Quantity"></span>
    <br />
    <input type="submit" value="Edit" />
</form>